### ISSUE TITLE
电报，切换全屏和非全屏，页面停留的电报位置不一样。（第一张为全屏，第二张为非全屏）

### ISSUE THREAD

**Issue by kstlp2005** [wangyazhen/CailianPressIssues#68]
![image](https://cloud.githubusercontent.com/assets/25195332/22680101/544ca692-ed41-11e6-93b3-ee268b6bd1ce.png)
![image](https://cloud.githubusercontent.com/assets/25195332/22680106/571968ec-ed41-11e6-982f-7059416a03cd.png)

**Comment by wangyazhen** [comment]
windows 版本也是一样的    并且切换全屏状态文章高度本来就会变化
